### ISSUE TITLE
Interactive HTML not valid on macOS / from RStudio

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightPlots#200]
Graph appears cut-off when exported from RStudio on macOS:

<img width="2560" alt="cutoff_bar" src="https://user-images.githubusercontent.com/5061277/80038853-8db8e400-854a-11ea-829a-e09cd8e4e023.png">

**Comment by tmelliott** [comment]
Double-checking this was fixed with latest gridSVG? @daniel-barnett

**Comment by daniel-barnett** [comment]
I'm still getting this particular error with gridSVG 1.7-2, but only with Chromium (Firefox works OK). No obvious JS errors with Chromium as it says "Load complete" in the console.

**Comment by tmelliott** [comment]
Weeird ... so it's OK from windows on all browsers? If it's just mac + chrome, I'll not worry about it.

**Comment by daniel-barnett** [comment]
Actually, I just had a go again and it seems to work OK when it's side-by-side. When it switches to the vertical layout, the top gets cut off in both Firefox and Chromium. I'm assuming this will then affect Windows/Linux in the same way but haven't checked yet

**Comment by tmelliott** [comment]
Are you testing with RStudio? I don't have it installed on linux, and it seems to be fine in both vertical and horizontal.

**Comment by daniel-barnett** [comment]
Yeah, that was with RStudio. Going through terminal it works fine when I tried it just now. 

I'm assuming this is something to do with the RStudioGD?

**Comment by tmelliott** [comment]
Possibly. Will leave here in case someone has the time/desire to investigate at a future date.
